### ISSUE TITLE
The bot doesn't work if you send a file that has the name with spaces

### ISSUE THREAD

**Issue by MarcosDevs** [adarsh-goel/Filestreambot-pro#12]
When a file is sent that has spaces in the name, the bot does not respond. I recommend using "quote" to fix this error.

**Comment by adarsh-goel** [comment]
fixed

**Comment by ElissonRodrigues** [comment]
The problem has not been fixed. The correction had nothing to do with the error. I will fork and send pull requests with the fix

**Comment by DeekshithSH** [comment]
> The problem has not been fixed. The correction had nothing to do with the error. I will fork and send pull requests with the fix
> 
> I'll be right back, thanks for the reply

- What Your Talking about,
About the Bot Generated Link or Something else

**Comment by ElissonRodrigues** [comment]
> > The problem has not been fixed. The correction had nothing to do with the error. I will fork and send pull requests with the fix
> > I'll be right back, thanks for the reply
> 
> * What Your Talking about,
>   About the Bot Generated Link or Something else

I sent the message to the wrong location, it was another repository 😅
