### ISSUE TITLE
Could you replace github url and follow me url with vars?

### ISSUE THREAD

**Issue by nicolerralph** [adarsh-goel/Filestreambot-pro#14]
its so hard to fork and refork everytime new update arrives
cannot merge

**Comment by adarsh-goel** [comment]
You can merge sir share the error if any at @agprojectschat and i will help

**Comment by adarsh-goel** [comment]
i can add vars but cant you fork and edit manually?

**Comment by nicolerralph** [comment]
i have edited manually.

**Comment by adarsh-goel** [comment]
so then?

**Comment by adarsh-goel** [comment]
why want vars

**Comment by nicolerralph** [comment]
but everytime new update arrive i cannot merge the update it has conflicts

**Comment by adarsh-goel** [comment]
share the ss of error

**Comment by nicolerralph** [comment]
i have deleted my fork and reforked it.cannot take ss now

**Comment by adarsh-goel** [comment]
ok whenever there is error feel free to message me : )

**Comment by nicolerralph** [comment]
ok
