### ISSUE TITLE
pymongo.errors.ConfigurationError: cannot open /etc/resolv.conf

### ISSUE THREAD

**Issue by MarcosDevs** [adarsh-goel/Filestreambot-pro#15]
# Error

pymongo.errors.ConfigurationError: cannot open /etc/resolv.conf

dnspython tries to open /etc/resolv.conf, which is prohibited on some devices. 

# Solution

https://github.com/adarsh-goel/Filestreambot-pro/blob/68417abc387435b64a18a2f2aad3dd21c6122b72/Adarsh/utils/database.py#L4

In the line above include:

``` python
import dns.resolver

dns.resolver.default_resolver=dns.resolver.Resolver(configure=False)
dns.resolver.default_resolver.nameservers=['1.1.1.1']
```

**Comment by adarsh-goel** [comment]
ok will add when free
