### ISSUE TITLE
The obtained link has no port bug

### ISSUE THREAD

**Issue by b1fly** [adarsh-goel/Filestreambot-pro#20]
The obtained link has no port bug

There is no response after adding the parameter of NO PORT. Remove the parameter of NO PORT. No matter whether it is added or not, the obtained download address does not have a port by default, and the webpage will prompt 404.

is bug?

I use TG-FileStreamBot for this project and did not find this problem
![image](https://user-images.githubusercontent.com/108970034/180794399-c1fbf2f4-c5d6-41e0-8f35-c9657f12ba2c.png)
![image](https://user-images.githubusercontent.com/108970034/180793909-73336bd1-1cb2-4891-ada6-1a0ecee7ea71.png)

**Comment by adarsh-goel** [comment]
oh god
NO_PORT accepts boolean value
do this
NO_PORT = False
PORT = 80
anyways port 80 is default port so adding it wont change output!

**Comment by b1fly** [comment]
> 哦上帝 NO_PORT 接受布尔值 这样做 NO_PORT = False PORT = 80 无论如何端口 80 是默认端口，所以添加它不会改变输出！

Thanks bro , i will try
