### ISSUE TITLE
Invalid parse mode "Markdown"

### ISSUE THREAD

**Issue by Fspb1gthub** [Adarsh-Goel/Filestreambot-pro#23]
The bot is not working on the channel
Instead bin shows this in Channel.👇
#ᴇʀʀᴏʀ_ᴛʀᴀᴄᴇʙᴀᴄᴋ: Invalid parse mode "Markdown"

Plz fix bro..

**Comment by Adarsh-Goel** [comment]
Ok will be fixed soon@

**Comment by Adarsh-Goel** [comment]
@Fspb1gthub please sync your fork the fix has been pushed

**Comment by Fspb1gthub** [comment]
> @Fspb1gthub please sync your fork the fix has been pushed
Bro.. error again
#ᴇʀʀᴏʀ_ᴛʀᴀᴄᴇʙᴀᴄᴋ: EditMessageReplyMarkup.edit_message_reply_markup() got an unexpected keyword argument 'id'
