### ISSUE TITLE
Error again 

### ISSUE THREAD

**Issue by Fspb1gthub** [Adarsh-Goel/Filestreambot-pro#24]
The bot is not working on the channel
Instead bin shows this in Channel.👇

#ᴇʀʀᴏʀ_ᴛʀᴀᴄᴇʙᴀᴄᴋ: EditMessageReplyMarkup.edit_message_reply_markup() got an unexpected keyword argument 'id'

**Comment by Adarsh-Goel** [comment]
now check!

**Comment by Fspb1gthub** [comment]
> now check!

#ᴇʀʀᴏʀ_ᴛʀᴀᴄᴇʙᴀᴄᴋ: name 'boradcast' is not defined

Error again😥

**Comment by Adarsh-Goel** [comment]
fixed!

**Comment by Adarsh-Goel** [comment]
https://github.com/Adarsh-Goel/Filestreambot-pro/commit/af95e1051644b2a8a182486da6d00d10f93e4be9

**Comment by Fspb1gthub** [comment]
> [af95e10](https://github.com/Adarsh-Goel/Filestreambot-pro/commit/af95e1051644b2a8a182486da6d00d10f93e4be9)
> 
> fixed!

Thanks bro

It is working now

https://telegra.ph/file/c881fb863a2b95819ba96.jpg

**Comment by Adarsh-Goel** [comment]
ok great
