### ISSUE TITLE
New Player

### ISSUE THREAD

**Issue by rubandurai27** [Adarsh-Goel/Filestreambot-pro#27]
Hi Bro . Can you add JW Video Player In Online Streaming & url Shorter Support

**Comment by Adarsh-Goel** [comment]
> Hi Bro . Can you add JW Video Player In Online Streaming & url Shorter Support

share an example of jw player with me I want to see how it looks and works.
also I wont add url shortener because the user should know where the link redirects to and these day people add paid shorteners which I am totally against off as they worsen the experience!

**Comment by rubandurai27** [comment]
Sample Video Html code 
<!DOCTYPE html>
<html>
<head>
    <script src='LINK_TO_YOUR_PLAYER'></script>
    <script>jwplayer.key='YOUR_KEY';</script>
</head>
<body>
    <div id="player">Loading the player...</div>
    <script>
        // Setup the player
        const player = jwplayer('player').setup({
            file: 'LINK_TO_YOUR_FILE.mp4'
        });

        // Listen to an event
        player.on('pause', (event) => {
            alert('Why did my user pause their video instead of watching it?');
        });

        // Call the API
        const bumpIt = () => {
            const vol = player.getVolume();
            player.setVolume(vol + 10);
        }
        bumpIt();
    </script>
</body>
</html>

For More information :
https://github.com/jwplayer/jwplayer

**Comment by eyMarv** [comment]
> Hi Bro . Can you add JW Video Player In Online Streaming & url Shorter Support

No jewplayer pls

**Comment by rubandurai27** [comment]
> > Hi Bro . Can you add JW Video Player In Online Streaming & url Shorter Support
> 
> No jewplayer pls

Y bro ?

**Comment by Adarsh-Goel** [comment]
> Y bro ?

I will try to add it only if you share with me a demo link of it.
In my opinion Plyr.io is best!

**Comment by rubandurai27** [comment]
https://github.com/Naysabots/Filestreambot-pro
See this Repo It's fully recoded. But Filename Option Not added . Add Filename Option & Shortner Support @Adarsh-Goel

**Comment by rubandurai27** [comment]
> > Y bro ?
> 
> I will try to add it only if you share with me a demo link of it. In my opinion Plyr.io is best!

https://codepen.io/lowkruc/pen/qRrEZp

**Comment by Adarsh-Goel** [comment]
wont be added as plyr.io is working and it isnt worth wasting time adding something which is fulfilled .

**Comment by Adarsh-Goel** [comment]
> https://github.com/Naysabots/Filestreambot-pro See this Repo It's fully recoded. But Filename Option Not added . Add Filename Option & Shortner Support @Adarsh-Goel

nothing is recoded just added 2-3 files which my code already has just relocated them
