### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rubandurai27** [Adarsh-Goel/Filestreambot-pro#31]
I am getting error

**Comment by rubandurai27** [comment]
![Screenshot_2022-09-06-20-20-04-184_com android chrome](https://user-images.githubusercontent.com/77948100/188667069-4905d640-8b8f-443c-9b54-b9c6a056a23e.jpg)

**Comment by eyMarv** [comment]
Cool

**Comment by Adarsh-Goel** [comment]
stop opening multiple comments @rubandurai27

**Comment by rubandurai27** [comment]
> stop opening multiple issues @rubandurai27

Sorry for that network issue

**Comment by rubandurai27** [comment]
> stop opening multiple issues @rubandurai27

![Screenshot_2022-09-07-07-08-55-309_org telegram plus](https://user-images.githubusercontent.com/77948100/188769818-2715a57c-23fd-468c-af4e-e0e5e5347895.jpg)

I am added Shortner feature . It's working fine . And trying to add streaming interface I am getting error

**Comment by rubandurai27** [comment]
> > stop opening multiple issues @rubandurai27
> 
> ![Screenshot_2022-09-07-07-08-55-309_org telegram plus](https://user-images.githubusercontent.com/77948100/188769818-2715a57c-23fd-468c-af4e-e0e5e5347895.jpg)
> 
> I am added Shortner feature . It's working fine . And trying to add streaming interface I am getting error

![Screenshot_2022-09-07-07-52-12-433_com android chrome](https://user-images.githubusercontent.com/77948100/188774444-9a1c12c1-90a0-4ce7-9db7-5c8394d70399.jpg)

**Comment by rubandurai27** [comment]
Please help me
