### ISSUE TITLE
Fail to Deploy on VPS

### ISSUE THREAD

**Issue by pakbottest** [Adarsh-Goel/Filestreambot-pro#41]
![image](https://user-images.githubusercontent.com/116292987/201465370-e3804e24-c041-48a2-abd7-7feacfd46c4c.png)

i'm facing that error while deploying on vps. Please help me to fix this problem.

Picture attached in this post

**Comment by pakbottest** [comment]
Help me to fix this issue

**Comment by Tanmay-dark** [comment]
You are supposed to full in .env you haven't added variables

**Comment by Adarsh-Goel** [comment]
> You are supposed to fill in .env you haven't added variables

Yes

**Comment by pakbottest** [comment]
brother bot is started but stream & download link is not working help me to fix this

**Comment by Adarsh-Goel** [comment]
Who will show the error?

**Comment by pakbottest** [comment]
brother when i open the link i'm getting that error
![image](https://user-images.githubusercontent.com/116292987/203328626-27e68ea9-a548-44aa-a409-7ac03c9cc354.png)

and here is the link that is generated

![image](https://user-images.githubusercontent.com/116292987/203328743-2d16d9bb-a1d0-4e5c-92fa-fdb9eae090f1.png)

**Comment by Adarsh-Goel** [comment]
Who will open the port?

**Comment by Adarsh-Goel** [comment]
Dude u opened 8080 and this link is for 80 port

**Comment by Adarsh-Goel** [comment]
Issues aren't meant for spoonfeeding better clean your mess yourself.

issues are meant to report bugs and code errors not your misconfiguration.

**Comment by pakbottest** [comment]
alright brother sorry for that

**Comment by Adarsh-Goel** [comment]
I have no time dude

**Comment by pakbottest** [comment]
when you got time bro then please do this.
it's Request bro
