### ISSUE TITLE
Deployment Error 

### ISSUE THREAD

**Issue by RubanDurai** [adarsh-goel/FileStreamBot-pro#55]
![Screenshot_2023-04-05-21-28-04-239_com android chrome](https://user-images.githubusercontent.com/77948100/230137245-25e504da-7dc4-4f29-a27b-d9f921e94913.jpg)

**Comment by Adarsh-Goel** [comment]
Try by removing runtime.txt from your forked repository

**Comment by Adarsh-Goel** [comment]
If that helps make a pull request
If it doesn't get fixed I will investigate further

**Comment by est-anime** [comment]
when deploying it shows app.json error

**Comment by Priya0178** [comment]
os error fu***k
