### ISSUE TITLE
Not Starting .

### ISSUE THREAD

**Issue by MinorX** [adarsh-goel/FileStreamBot-pro#58]
Saw this same problem at #21
I've cross checked config.env multiple times. It's in the root directory and in the /Adarsh directory as well. Same error. Cannot resolve. You know what's happening ?

**Comment by adarsh-goel** [comment]
Still facing this problem?

**Comment by Yashx2** [comment]
Could be. Im not using this now. I don't have idea of current situation

**Comment by MinorX** [comment]
Could be. Im not using this now. I don't have idea of current situation
